### PR TITLE
Update README.md to include the streaming decoder change

### PR DESCRIPTION
**Pull request by Umar-M-Haroon**
Based on the [tweet](https://twitter.com/_saagarjha/status/1648017484740714498?s=20), adding some docs so people know how to best use unxip 2.1

### CODE REVIEW

**Comment by saagarjha** [comment]
This is very similar to #33 by @mfaani. I'm fine with putting details of how to use the streaming decoder in the README but I feel like the best way to merge the two efforts and match what I'm looking for is for me to author the commit myself and stick both of your names on it. What do you think?

**Comment by mfaani** [comment]
Yeah go for it.

**Comment by Umar-M-Haroon** [comment]
works for me! I feel like you can explain it better than I can haha

**Comment by saagarjha** [comment]
````diff
diff --git a/README.md b/README.md
index dbf7f83..03c55be 100644
--- a/README.md
+++ b/README.md
@@ -41,9 +41,13 @@ The intended usage of unxip is with a single command line parameter that represe
 
 ```console
 $ unxip Xcode.xip # will produce Xcode.app in the current directory
+$ curl https://webserver/Xcode.xip | unxip - /Applications # Read from a stream and extract to /Applications
 ```
 
-As the tool is still somewhat rough, its error handling is not very good at the moment. An attempt has been made to at least crash preemptively when things go wrong, but you may still run into strange behavior on edge cases. For best results, ensure that the directory you are running unxip from does not contain any existing Xcode(-beta).app bundles and that you are using a modern version of macOS on a fast APFS filesystem. **For simplicity, unxip does not perform any signature verification, so if authentication is important you should use another mechanism (such as a checksum) for validation.**
+As the tool is still somewhat rough, its error handling is not very good at the moment. An attempt has been made to at least crash preemptively when things go wrong, but you may still run into strange behavior on edge cases. For best results, ensure that the directory you are running unxip from does not contain any existing Xcode(-beta).app bundles and that you are using a modern version of macOS on a fast APFS filesystem.
+
+> **Warning**
+> For simplicity, unxip does not perform any signature verification, so if authentication is important you should use another mechanism (such as a checksum) for validation. Consider downloading XIPs only from sources you trust, such as directly from Apple.
 
 ## Contributing
 
````
     
I plan to go with this; feel free to accept as little or as much credit of it as you'd like. You will notice I have chosen to not include how to make an authenticated request for XIP files: since this is subject to change and readily available online, I do not feel it is appropriate to include it here.

**Comment by Umar-M-Haroon** [comment]
LGTM 👍

**Comment by saagarjha** [comment]
This is in the README now as https://github.com/saagarjha/unxip/commit/350635c53e45f77cb329ae592a84e954d21a0d6e

**Pull request closed without merging**
